// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: classifier.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSellerClassification = `-- name: GetSellerClassification :one
SELECT seller_id, olx_user_id, display_name, is_business, registered_at, listings_active, districts_count, cities_count, score_personhood, score_listings_count, score_geography, score_account_age, real_seller_score FROM seller_classifications
 WHERE olx_user_id = $1
`

// Single seller's score and component breakdown.
func (q *Queries) GetSellerClassification(ctx context.Context, olxUserID string) (SellerClassification, error) {
	row := q.db.QueryRow(ctx, getSellerClassification, olxUserID)
	var i SellerClassification
	err := row.Scan(
		&i.SellerID,
		&i.OlxUserID,
		&i.DisplayName,
		&i.IsBusiness,
		&i.RegisteredAt,
		&i.ListingsActive,
		&i.DistrictsCount,
		&i.CitiesCount,
		&i.ScorePersonhood,
		&i.ScoreListingsCount,
		&i.ScoreGeography,
		&i.ScoreAccountAge,
		&i.RealSellerScore,
	)
	return i, err
}

const getSellerCounts = `-- name: GetSellerCounts :many
SELECT
    is_business,
    COUNT(*)::int                 AS sellers,
    AVG(real_seller_score)::float AS avg_score
FROM seller_classifications
GROUP BY is_business
`

type GetSellerCountsRow struct {
	IsBusiness bool    `json:"is_business"`
	Sellers    int32   `json:"sellers"`
	AvgScore   float64 `json:"avg_score"`
}

// Two rows: one for is_business=false, one for true. Used by the API's
// stats endpoint to render the private/business split.
func (q *Queries) GetSellerCounts(ctx context.Context) ([]GetSellerCountsRow, error) {
	rows, err := q.db.Query(ctx, getSellerCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSellerCountsRow
	for rows.Next() {
		var i GetSellerCountsRow
		if err := rows.Scan(&i.IsBusiness, &i.Sellers, &i.AvgScore); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listListingsForAPI = `-- name: ListListingsForAPI :many
SELECT listing_id, olx_listing_id, url, title, price, currency, city, district, posted_at, listing_last_seen, seller_id, olx_user_id, seller_name, is_business, seller_registered_at, seller_listings_active, seller_districts_count, real_seller_score FROM listings_with_classification
 WHERE posted_at >= NOW() - (interval '1 day' * $1::int)
   AND real_seller_score >= $2::numeric
 ORDER BY real_seller_score DESC, posted_at DESC
 LIMIT $3::int
`

type ListListingsForAPIParams struct {
	MaxAgeDays int32          `json:"max_age_days"`
	MinScore   pgtype.Numeric `json:"min_score"`
	LimitN     int32          `json:"limit_n"`
}

// The HTTP API's main query: filtered listings with their seller score.
// max_age_days = 99999 effectively disables the recency filter (NOW() -
// 273 years catches everything in practice).
func (q *Queries) ListListingsForAPI(ctx context.Context, arg ListListingsForAPIParams) ([]ListingsWithClassification, error) {
	rows, err := q.db.Query(ctx, listListingsForAPI, arg.MaxAgeDays, arg.MinScore, arg.LimitN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListingsWithClassification
	for rows.Next() {
		var i ListingsWithClassification
		if err := rows.Scan(
			&i.ListingID,
			&i.OlxListingID,
			&i.Url,
			&i.Title,
			&i.Price,
			&i.Currency,
			&i.City,
			&i.District,
			&i.PostedAt,
			&i.ListingLastSeen,
			&i.SellerID,
			&i.OlxUserID,
			&i.SellerName,
			&i.IsBusiness,
			&i.SellerRegisteredAt,
			&i.SellerListingsActive,
			&i.SellerDistrictsCount,
			&i.RealSellerScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshSellerStats = `-- name: RefreshSellerStats :exec
REFRESH MATERIALIZED VIEW CONCURRENTLY seller_stats
`

// Refresh the materialized view that the classifier reads from. Run after
// a batch of new listings has been parsed and before re-running classify.
// CONCURRENTLY needs the UNIQUE index that 0001_init.sql declares.
func (q *Queries) RefreshSellerStats(ctx context.Context) error {
	_, err := q.db.Exec(ctx, refreshSellerStats)
	return err
}

const topRealSellers = `-- name: TopRealSellers :many
SELECT seller_id, olx_user_id, display_name, is_business, registered_at, listings_active, districts_count, cities_count, score_personhood, score_listings_count, score_geography, score_account_age, real_seller_score FROM seller_classifications
 WHERE listings_active >= $1::int
 ORDER BY real_seller_score DESC, listings_active DESC, seller_id ASC
 LIMIT $2::int
`

type TopRealSellersParams struct {
	MinActiveListings int32 `json:"min_active_listings"`
	Limit             int32 `json:"limit"`
}

// Returns the top-N sellers by real_seller_score, used by `cmd/classify`.
// Ties broken by listings_active DESC so the ranking is deterministic
// (otherwise PostgreSQL's row order on equal scores is implementation-defined).
func (q *Queries) TopRealSellers(ctx context.Context, arg TopRealSellersParams) ([]SellerClassification, error) {
	rows, err := q.db.Query(ctx, topRealSellers, arg.MinActiveListings, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SellerClassification
	for rows.Next() {
		var i SellerClassification
		if err := rows.Scan(
			&i.SellerID,
			&i.OlxUserID,
			&i.DisplayName,
			&i.IsBusiness,
			&i.RegisteredAt,
			&i.ListingsActive,
			&i.DistrictsCount,
			&i.CitiesCount,
			&i.ScorePersonhood,
			&i.ScoreListingsCount,
			&i.ScoreGeography,
			&i.ScoreAccountAge,
			&i.RealSellerScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
