// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: classifier.sql

package sqlc

import (
	"context"
)

const getSellerClassification = `-- name: GetSellerClassification :one
SELECT seller_id, olx_user_id, display_name, is_business, registered_at, listings_active, districts_count, cities_count, score_personhood, score_listings_count, score_geography, score_account_age, real_seller_score FROM seller_classifications
 WHERE olx_user_id = $1
`

// Single seller's score and component breakdown.
func (q *Queries) GetSellerClassification(ctx context.Context, olxUserID string) (SellerClassification, error) {
	row := q.db.QueryRow(ctx, getSellerClassification, olxUserID)
	var i SellerClassification
	err := row.Scan(
		&i.SellerID,
		&i.OlxUserID,
		&i.DisplayName,
		&i.IsBusiness,
		&i.RegisteredAt,
		&i.ListingsActive,
		&i.DistrictsCount,
		&i.CitiesCount,
		&i.ScorePersonhood,
		&i.ScoreListingsCount,
		&i.ScoreGeography,
		&i.ScoreAccountAge,
		&i.RealSellerScore,
	)
	return i, err
}

const refreshSellerStats = `-- name: RefreshSellerStats :exec
REFRESH MATERIALIZED VIEW CONCURRENTLY seller_stats
`

// Refresh the materialized view that the classifier reads from. Run after
// a batch of new listings has been parsed and before re-running classify.
// CONCURRENTLY needs the UNIQUE index that 0001_init.sql declares.
func (q *Queries) RefreshSellerStats(ctx context.Context) error {
	_, err := q.db.Exec(ctx, refreshSellerStats)
	return err
}

const topRealSellers = `-- name: TopRealSellers :many
SELECT seller_id, olx_user_id, display_name, is_business, registered_at, listings_active, districts_count, cities_count, score_personhood, score_listings_count, score_geography, score_account_age, real_seller_score FROM seller_classifications
 WHERE listings_active >= $1::int
 ORDER BY real_seller_score DESC, listings_active DESC, seller_id ASC
 LIMIT $2::int
`

type TopRealSellersParams struct {
	MinActiveListings int32 `json:"min_active_listings"`
	Limit             int32 `json:"limit"`
}

// Returns the top-N sellers by real_seller_score, used by `cmd/classify`.
// Ties broken by listings_active DESC so the ranking is deterministic
// (otherwise PostgreSQL's row order on equal scores is implementation-defined).
func (q *Queries) TopRealSellers(ctx context.Context, arg TopRealSellersParams) ([]SellerClassification, error) {
	rows, err := q.db.Query(ctx, topRealSellers, arg.MinActiveListings, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SellerClassification
	for rows.Next() {
		var i SellerClassification
		if err := rows.Scan(
			&i.SellerID,
			&i.OlxUserID,
			&i.DisplayName,
			&i.IsBusiness,
			&i.RegisteredAt,
			&i.ListingsActive,
			&i.DistrictsCount,
			&i.CitiesCount,
			&i.ScorePersonhood,
			&i.ScoreListingsCount,
			&i.ScoreGeography,
			&i.ScoreAccountAge,
			&i.RealSellerScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
