// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: classifier.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDistinctCategories = `-- name: GetDistinctCategories :many
SELECT property_type, deal_type, COUNT(*)::int AS n
  FROM listings_with_classification
 WHERE property_type IS NOT NULL AND property_type <> ''
 GROUP BY property_type, deal_type
 ORDER BY n DESC, property_type
`

type GetDistinctCategoriesRow struct {
	PropertyType pgtype.Text `json:"property_type"`
	DealType     pgtype.Text `json:"deal_type"`
	N            int32       `json:"n"`
}

// Distinct (property_type, deal_type) pairs present in the dataset, used
// to populate the frontend dropdowns dynamically (no hardcoded list).
func (q *Queries) GetDistinctCategories(ctx context.Context) ([]GetDistinctCategoriesRow, error) {
	rows, err := q.db.Query(ctx, getDistinctCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDistinctCategoriesRow
	for rows.Next() {
		var i GetDistinctCategoriesRow
		if err := rows.Scan(&i.PropertyType, &i.DealType, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctCities = `-- name: GetDistinctCities :many
SELECT city, COUNT(*)::int AS n
  FROM listings_with_classification
 WHERE city IS NOT NULL AND city <> ''
 GROUP BY city
 ORDER BY n DESC, city
`

type GetDistinctCitiesRow struct {
	City pgtype.Text `json:"city"`
	N    int32       `json:"n"`
}

// Cities present in the dataset with their listing counts, drives the
// frontend's city dropdown. City names are whatever OLX wrote
// (Ukrainian: "Київ", "Львів", "Одеса", etc.) — we don't normalize.
func (q *Queries) GetDistinctCities(ctx context.Context) ([]GetDistinctCitiesRow, error) {
	rows, err := q.db.Query(ctx, getDistinctCities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDistinctCitiesRow
	for rows.Next() {
		var i GetDistinctCitiesRow
		if err := rows.Scan(&i.City, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastParsedAt = `-- name: GetLastParsedAt :one
SELECT MAX(last_scraped_at) AS last_parsed_at FROM listings
`

// When was the last time the parser committed a listing.
// Used to show "data as of X" in the UI.
func (q *Queries) GetLastParsedAt(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, getLastParsedAt)
	var last_parsed_at interface{}
	err := row.Scan(&last_parsed_at)
	return last_parsed_at, err
}

const getSellerClassification = `-- name: GetSellerClassification :one
SELECT seller_id, olx_user_id, display_name, is_business, registered_at, listings_active, districts_count, cities_count, score_personhood, score_listings_count, score_geography, score_account_age, real_seller_score, manual_label FROM seller_classifications
 WHERE olx_user_id = $1
`

// Single seller's score and component breakdown.
func (q *Queries) GetSellerClassification(ctx context.Context, olxUserID string) (SellerClassification, error) {
	row := q.db.QueryRow(ctx, getSellerClassification, olxUserID)
	var i SellerClassification
	err := row.Scan(
		&i.SellerID,
		&i.OlxUserID,
		&i.DisplayName,
		&i.IsBusiness,
		&i.RegisteredAt,
		&i.ListingsActive,
		&i.DistrictsCount,
		&i.CitiesCount,
		&i.ScorePersonhood,
		&i.ScoreListingsCount,
		&i.ScoreGeography,
		&i.ScoreAccountAge,
		&i.RealSellerScore,
		&i.ManualLabel,
	)
	return i, err
}

const getSellerCounts = `-- name: GetSellerCounts :many
SELECT
    is_business,
    COUNT(*)::int                 AS sellers,
    AVG(real_seller_score)::float AS avg_score
FROM seller_classifications
GROUP BY is_business
`

type GetSellerCountsRow struct {
	IsBusiness bool    `json:"is_business"`
	Sellers    int32   `json:"sellers"`
	AvgScore   float64 `json:"avg_score"`
}

// Two rows: one for is_business=false, one for true. Used by the API's
// stats endpoint to render the private/business split.
func (q *Queries) GetSellerCounts(ctx context.Context) ([]GetSellerCountsRow, error) {
	rows, err := q.db.Query(ctx, getSellerCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSellerCountsRow
	for rows.Next() {
		var i GetSellerCountsRow
		if err := rows.Scan(&i.IsBusiness, &i.Sellers, &i.AvgScore); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const labelSeller = `-- name: LabelSeller :exec
UPDATE sellers
   SET manual_label = NULLIF($1::text, ''),
       updated_at   = NOW()
 WHERE olx_user_id  = $2
`

type LabelSellerParams struct {
	ManualLabel string `json:"manual_label"`
	OlxUserID   string `json:"olx_user_id"`
}

// Set or clear a manual label ('owner', 'agency', or "" to remove).
// NULLIF converts empty string to NULL so the caller never needs to
// distinguish between "set null" and "set empty string".
func (q *Queries) LabelSeller(ctx context.Context, arg LabelSellerParams) error {
	_, err := q.db.Exec(ctx, labelSeller, arg.ManualLabel, arg.OlxUserID)
	return err
}

const listListingsForAPI = `-- name: ListListingsForAPI :many
SELECT listing_id, olx_listing_id, url, title, price, currency, city, district, posted_at, listing_last_seen, seller_id, olx_user_id, seller_name, is_business, seller_registered_at, seller_listings_active, seller_districts_count, real_seller_score, property_type, deal_type, manual_label FROM listings_with_classification
 WHERE posted_at >= NOW() - (interval '1 day' * $1::int)
   AND real_seller_score >= $2::numeric
   AND ($3::text = '' OR property_type = $3::text)
   AND ($4::text     = '' OR deal_type     = $4::text)
   AND ($5::text          = '' OR city          = $5::text)
 ORDER BY real_seller_score DESC, posted_at DESC
 LIMIT $6::int
`

type ListListingsForAPIParams struct {
	MaxAgeDays   int32          `json:"max_age_days"`
	MinScore     pgtype.Numeric `json:"min_score"`
	PropertyType string         `json:"property_type"`
	DealType     string         `json:"deal_type"`
	City         string         `json:"city"`
	LimitN       int32          `json:"limit_n"`
}

// The HTTP API's main query: filtered listings with their seller score.
// max_age_days = 99999 effectively disables the recency filter (NOW() -
// 273 years catches everything in practice).
//
// property_type and deal_type are "empty string = no filter" — if the
// caller passes ”, the OR-branch short-circuits and all rows pass; if
// they pass a concrete value (e.g. 'квартири'), only matching rows do.
// NULL property_type / deal_type rows are excluded when a filter is set,
// which is what we want: filtering on a category implies "give me data
// that actually carries that category".
func (q *Queries) ListListingsForAPI(ctx context.Context, arg ListListingsForAPIParams) ([]ListingsWithClassification, error) {
	rows, err := q.db.Query(ctx, listListingsForAPI,
		arg.MaxAgeDays,
		arg.MinScore,
		arg.PropertyType,
		arg.DealType,
		arg.City,
		arg.LimitN,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListingsWithClassification
	for rows.Next() {
		var i ListingsWithClassification
		if err := rows.Scan(
			&i.ListingID,
			&i.OlxListingID,
			&i.Url,
			&i.Title,
			&i.Price,
			&i.Currency,
			&i.City,
			&i.District,
			&i.PostedAt,
			&i.ListingLastSeen,
			&i.SellerID,
			&i.OlxUserID,
			&i.SellerName,
			&i.IsBusiness,
			&i.SellerRegisteredAt,
			&i.SellerListingsActive,
			&i.SellerDistrictsCount,
			&i.RealSellerScore,
			&i.PropertyType,
			&i.DealType,
			&i.ManualLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshSellerStats = `-- name: RefreshSellerStats :exec
REFRESH MATERIALIZED VIEW CONCURRENTLY seller_stats
`

// Refresh the materialized view that the classifier reads from. Run after
// a batch of new listings has been parsed and before re-running classify.
// CONCURRENTLY needs the UNIQUE index that 0001_init.sql declares.
func (q *Queries) RefreshSellerStats(ctx context.Context) error {
	_, err := q.db.Exec(ctx, refreshSellerStats)
	return err
}

const topRealSellers = `-- name: TopRealSellers :many
SELECT seller_id, olx_user_id, display_name, is_business, registered_at, listings_active, districts_count, cities_count, score_personhood, score_listings_count, score_geography, score_account_age, real_seller_score, manual_label FROM seller_classifications
 WHERE listings_active >= $1::int
 ORDER BY real_seller_score DESC, listings_active DESC, seller_id ASC
 LIMIT $2::int
`

type TopRealSellersParams struct {
	MinActiveListings int32 `json:"min_active_listings"`
	Limit             int32 `json:"limit"`
}

// Returns the top-N sellers by real_seller_score, used by `cmd/classify`.
// Ties broken by listings_active DESC so the ranking is deterministic
// (otherwise PostgreSQL's row order on equal scores is implementation-defined).
func (q *Queries) TopRealSellers(ctx context.Context, arg TopRealSellersParams) ([]SellerClassification, error) {
	rows, err := q.db.Query(ctx, topRealSellers, arg.MinActiveListings, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SellerClassification
	for rows.Next() {
		var i SellerClassification
		if err := rows.Scan(
			&i.SellerID,
			&i.OlxUserID,
			&i.DisplayName,
			&i.IsBusiness,
			&i.RegisteredAt,
			&i.ListingsActive,
			&i.DistrictsCount,
			&i.CitiesCount,
			&i.ScorePersonhood,
			&i.ScoreListingsCount,
			&i.ScoreGeography,
			&i.ScoreAccountAge,
			&i.RealSellerScore,
			&i.ManualLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
