// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fetches.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFetchByID = `-- name: GetFetchByID :one
SELECT id, url, status_code, html, headers, error, fetched_at FROM listing_html_fetches WHERE id = $1
`

func (q *Queries) GetFetchByID(ctx context.Context, id int64) (ListingHtmlFetch, error) {
	row := q.db.QueryRow(ctx, getFetchByID, id)
	var i ListingHtmlFetch
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.StatusCode,
		&i.Html,
		&i.Headers,
		&i.Error,
		&i.FetchedAt,
	)
	return i, err
}

const getLatestFetchByURL = `-- name: GetLatestFetchByURL :one
SELECT id, url, status_code, html, headers, error, fetched_at FROM listing_html_fetches
WHERE url = $1
ORDER BY fetched_at DESC
LIMIT 1
`

func (q *Queries) GetLatestFetchByURL(ctx context.Context, url string) (ListingHtmlFetch, error) {
	row := q.db.QueryRow(ctx, getLatestFetchByURL, url)
	var i ListingHtmlFetch
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.StatusCode,
		&i.Html,
		&i.Headers,
		&i.Error,
		&i.FetchedAt,
	)
	return i, err
}

const insertFetch = `-- name: InsertFetch :one
INSERT INTO listing_html_fetches (
    url, status_code, html, headers, error
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, url, status_code, html, headers, error, fetched_at
`

type InsertFetchParams struct {
	Url        string          `json:"url"`
	StatusCode int16           `json:"status_code"`
	Html       []byte          `json:"html"`
	Headers    json.RawMessage `json:"headers"`
	Error      pgtype.Text     `json:"error"`
}

// Append-only: every fetch attempt that lands here gets a new row.
// The fetcher writes successes (status 2xx, body present) and permanent
// failures (4xx, body NULL). Transient failures are NOT stored here —
// they live in retry queues + application logs.
func (q *Queries) InsertFetch(ctx context.Context, arg InsertFetchParams) (ListingHtmlFetch, error) {
	row := q.db.QueryRow(ctx, insertFetch,
		arg.Url,
		arg.StatusCode,
		arg.Html,
		arg.Headers,
		arg.Error,
	)
	var i ListingHtmlFetch
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.StatusCode,
		&i.Html,
		&i.Headers,
		&i.Error,
		&i.FetchedAt,
	)
	return i, err
}
