// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listings.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countListings = `-- name: CountListings :one
SELECT COUNT(*) FROM listings
`

func (q *Queries) CountListings(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countListings)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getListingByOlxID = `-- name: GetListingByOlxID :one
SELECT id, olx_listing_id, seller_id, url, title, description, price, currency, deal_type, property_type, rooms, area_total, area_living, floor, floors_total, city, district, address, lat, lon, posted_at, updated_at_remote, status, attributes, raw, first_seen_at, last_seen_at, last_scraped_at, created_at, updated_at FROM listings WHERE olx_listing_id = $1
`

func (q *Queries) GetListingByOlxID(ctx context.Context, olxListingID string) (Listing, error) {
	row := q.db.QueryRow(ctx, getListingByOlxID, olxListingID)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.OlxListingID,
		&i.SellerID,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Currency,
		&i.DealType,
		&i.PropertyType,
		&i.Rooms,
		&i.AreaTotal,
		&i.AreaLiving,
		&i.Floor,
		&i.FloorsTotal,
		&i.City,
		&i.District,
		&i.Address,
		&i.Lat,
		&i.Lon,
		&i.PostedAt,
		&i.UpdatedAtRemote,
		&i.Status,
		&i.Attributes,
		&i.Raw,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.LastScrapedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertListingSnapshot = `-- name: InsertListingSnapshot :execrows
INSERT INTO listing_snapshots (
    listing_id, price, currency, status, title, raw_hash
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (listing_id, raw_hash) DO NOTHING
`

type InsertListingSnapshotParams struct {
	ListingID int64          `json:"listing_id"`
	Price     pgtype.Numeric `json:"price"`
	Currency  pgtype.Text    `json:"currency"`
	Status    pgtype.Text    `json:"status"`
	Title     pgtype.Text    `json:"title"`
	RawHash   string         `json:"raw_hash"`
}

// Append-only history of (price, status, title) changes per listing.
// The unique constraint on (listing_id, raw_hash) means re-parsing an
// unchanged listing is a no-op; only real changes create new rows.
func (q *Queries) InsertListingSnapshot(ctx context.Context, arg InsertListingSnapshotParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertListingSnapshot,
		arg.ListingID,
		arg.Price,
		arg.Currency,
		arg.Status,
		arg.Title,
		arg.RawHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertListing = `-- name: UpsertListing :one
INSERT INTO listings (
    olx_listing_id,
    seller_id,
    url,
    title,
    description,
    price,
    currency,
    status,
    deal_type,
    property_type,
    city,
    district,
    address,
    lat,
    lon,
    posted_at,
    attributes,
    raw,
    last_scraped_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15,
    $16, $17, $18, NOW()
)
ON CONFLICT (olx_listing_id) DO UPDATE SET
    seller_id     = EXCLUDED.seller_id,
    title         = EXCLUDED.title,
    description   = EXCLUDED.description,
    price         = EXCLUDED.price,
    currency      = EXCLUDED.currency,
    status        = EXCLUDED.status,
    deal_type     = EXCLUDED.deal_type,
    property_type = EXCLUDED.property_type,
    city          = EXCLUDED.city,
    district      = EXCLUDED.district,
    address       = EXCLUDED.address,
    lat           = EXCLUDED.lat,
    lon           = EXCLUDED.lon,
    posted_at     = EXCLUDED.posted_at,
    attributes    = EXCLUDED.attributes,
    raw           = EXCLUDED.raw,
    last_seen_at  = NOW(),
    last_scraped_at = NOW()
RETURNING id, olx_listing_id, seller_id, url, title, description, price, currency, deal_type, property_type, rooms, area_total, area_living, floor, floors_total, city, district, address, lat, lon, posted_at, updated_at_remote, status, attributes, raw, first_seen_at, last_seen_at, last_scraped_at, created_at, updated_at
`

type UpsertListingParams struct {
	OlxListingID string             `json:"olx_listing_id"`
	SellerID     pgtype.Int8        `json:"seller_id"`
	Url          string             `json:"url"`
	Title        pgtype.Text        `json:"title"`
	Description  pgtype.Text        `json:"description"`
	Price        pgtype.Numeric     `json:"price"`
	Currency     pgtype.Text        `json:"currency"`
	Status       string             `json:"status"`
	DealType     pgtype.Text        `json:"deal_type"`
	PropertyType pgtype.Text        `json:"property_type"`
	City         pgtype.Text        `json:"city"`
	District     pgtype.Text        `json:"district"`
	Address      pgtype.Text        `json:"address"`
	Lat          pgtype.Float8      `json:"lat"`
	Lon          pgtype.Float8      `json:"lon"`
	PostedAt     pgtype.Timestamptz `json:"posted_at"`
	Attributes   json.RawMessage    `json:"attributes"`
	Raw          json.RawMessage    `json:"raw"`
}

// Insert or update by olx_listing_id. Same timestamp semantics as sellers:
// created_at / first_seen_at frozen on insert, last_seen_at / last_scraped_at
// bumped on every call, updated_at handled by the trigger.
func (q *Queries) UpsertListing(ctx context.Context, arg UpsertListingParams) (Listing, error) {
	row := q.db.QueryRow(ctx, upsertListing,
		arg.OlxListingID,
		arg.SellerID,
		arg.Url,
		arg.Title,
		arg.Description,
		arg.Price,
		arg.Currency,
		arg.Status,
		arg.DealType,
		arg.PropertyType,
		arg.City,
		arg.District,
		arg.Address,
		arg.Lat,
		arg.Lon,
		arg.PostedAt,
		arg.Attributes,
		arg.Raw,
	)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.OlxListingID,
		&i.SellerID,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Currency,
		&i.DealType,
		&i.PropertyType,
		&i.Rooms,
		&i.AreaTotal,
		&i.AreaLiving,
		&i.Floor,
		&i.FloorsTotal,
		&i.City,
		&i.District,
		&i.Address,
		&i.Lat,
		&i.Lon,
		&i.PostedAt,
		&i.UpdatedAtRemote,
		&i.Status,
		&i.Attributes,
		&i.Raw,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.LastScrapedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
