// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type Listing struct {
	ID              int64              `json:"id"`
	OlxListingID    string             `json:"olx_listing_id"`
	SellerID        pgtype.Int8        `json:"seller_id"`
	Url             string             `json:"url"`
	Title           pgtype.Text        `json:"title"`
	Description     pgtype.Text        `json:"description"`
	Price           pgtype.Numeric     `json:"price"`
	Currency        pgtype.Text        `json:"currency"`
	DealType        pgtype.Text        `json:"deal_type"`
	PropertyType    pgtype.Text        `json:"property_type"`
	Rooms           pgtype.Int2        `json:"rooms"`
	AreaTotal       pgtype.Numeric     `json:"area_total"`
	AreaLiving      pgtype.Numeric     `json:"area_living"`
	Floor           pgtype.Int2        `json:"floor"`
	FloorsTotal     pgtype.Int2        `json:"floors_total"`
	City            pgtype.Text        `json:"city"`
	District        pgtype.Text        `json:"district"`
	Address         pgtype.Text        `json:"address"`
	Lat             pgtype.Float8      `json:"lat"`
	Lon             pgtype.Float8      `json:"lon"`
	PostedAt        pgtype.Timestamptz `json:"posted_at"`
	UpdatedAtRemote pgtype.Timestamptz `json:"updated_at_remote"`
	Status          string             `json:"status"`
	Attributes      json.RawMessage    `json:"attributes"`
	Raw             json.RawMessage    `json:"raw"`
	FirstSeenAt     pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt      pgtype.Timestamptz `json:"last_seen_at"`
	LastScrapedAt   pgtype.Timestamptz `json:"last_scraped_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ListingHtmlFetch struct {
	ID         int64              `json:"id"`
	Url        string             `json:"url"`
	StatusCode int16              `json:"status_code"`
	Html       []byte             `json:"html"`
	Headers    json.RawMessage    `json:"headers"`
	Error      pgtype.Text        `json:"error"`
	FetchedAt  pgtype.Timestamptz `json:"fetched_at"`
}

type ListingPhoto struct {
	ID        int64              `json:"id"`
	ListingID int64              `json:"listing_id"`
	Url       string             `json:"url"`
	Position  int16              `json:"position"`
	Phash     pgtype.Text        `json:"phash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ListingSnapshot struct {
	ID         int64              `json:"id"`
	ListingID  int64              `json:"listing_id"`
	Price      pgtype.Numeric     `json:"price"`
	Currency   pgtype.Text        `json:"currency"`
	Status     pgtype.Text        `json:"status"`
	Title      pgtype.Text        `json:"title"`
	RawHash    string             `json:"raw_hash"`
	CapturedAt pgtype.Timestamptz `json:"captured_at"`
}

type ScrapeJob struct {
	ID         int64              `json:"id"`
	Kind       string             `json:"kind"`
	Target     string             `json:"target"`
	Status     string             `json:"status"`
	Attempt    int32              `json:"attempt"`
	Error      pgtype.Text        `json:"error"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Seller struct {
	ID             int64              `json:"id"`
	OlxUserID      string             `json:"olx_user_id"`
	DisplayName    pgtype.Text        `json:"display_name"`
	ProfileUrl     pgtype.Text        `json:"profile_url"`
	RegisteredAt   pgtype.Timestamptz `json:"registered_at"`
	IsBusiness     bool               `json:"is_business"`
	PhoneHash      pgtype.Text        `json:"phone_hash"`
	AvatarUrl      pgtype.Text        `json:"avatar_url"`
	Location       pgtype.Text        `json:"location"`
	Raw            json.RawMessage    `json:"raw"`
	FirstSeenAt    pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt     pgtype.Timestamptz `json:"last_seen_at"`
	LastScrapedAt  pgtype.Timestamptz `json:"last_scraped_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	LastEnrichedAt pgtype.Timestamptz `json:"last_enriched_at"`
}

type SellerClassification struct {
	SellerID           int64              `json:"seller_id"`
	OlxUserID          string             `json:"olx_user_id"`
	DisplayName        pgtype.Text        `json:"display_name"`
	IsBusiness         bool               `json:"is_business"`
	RegisteredAt       pgtype.Timestamptz `json:"registered_at"`
	ListingsActive     int64              `json:"listings_active"`
	DistrictsCount     int64              `json:"districts_count"`
	CitiesCount        int64              `json:"cities_count"`
	ScorePersonhood    pgtype.Numeric     `json:"score_personhood"`
	ScoreListingsCount pgtype.Numeric     `json:"score_listings_count"`
	ScoreGeography     pgtype.Numeric     `json:"score_geography"`
	ScoreAccountAge    pgtype.Numeric     `json:"score_account_age"`
	RealSellerScore    pgtype.Numeric     `json:"real_seller_score"`
}

type SellerStat struct {
	SellerID       int64       `json:"seller_id"`
	OlxUserID      string      `json:"olx_user_id"`
	IsBusiness     bool        `json:"is_business"`
	ListingsTotal  int64       `json:"listings_total"`
	ListingsActive int64       `json:"listings_active"`
	DistrictsCount int64       `json:"districts_count"`
	CitiesCount    int64       `json:"cities_count"`
	FirstListingAt interface{} `json:"first_listing_at"`
	LastListingAt  interface{} `json:"last_listing_at"`
}
