// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CountSellers(ctx context.Context) (int64, error)
	GetFetchByID(ctx context.Context, id int64) (ListingHtmlFetch, error)
	GetLatestFetchByURL(ctx context.Context, url string) (ListingHtmlFetch, error)
	GetSellerByOlxID(ctx context.Context, olxUserID string) (Seller, error)
	// Append-only: every fetch attempt that lands here gets a new row.
	// The fetcher writes successes (status 2xx, body present) and permanent
	// failures (4xx, body NULL). Transient failures are NOT stored here —
	// they live in retry queues + application logs.
	InsertFetch(ctx context.Context, arg InsertFetchParams) (ListingHtmlFetch, error)
	// Insert a seller, or update the mutable fields if olx_user_id already
	// exists. last_seen_at and last_scraped_at are bumped to NOW() on both
	// insert and update; first_seen_at / created_at stay frozen (the schema
	// defaults handle the insert case, ON CONFLICT leaves them untouched).
	// updated_at is bumped automatically by the sellers_set_updated_at trigger.
	UpsertSeller(ctx context.Context, arg UpsertSellerParams) (Seller, error)
}

var _ Querier = (*Queries)(nil)
