// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sellers.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSellers = `-- name: CountSellers :one
SELECT COUNT(*) FROM sellers
`

func (q *Queries) CountSellers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSellers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSellerByOlxID = `-- name: GetSellerByOlxID :one
SELECT id, olx_user_id, display_name, profile_url, registered_at, is_business, phone_hash, avatar_url, location, raw, first_seen_at, last_seen_at, last_scraped_at, created_at, updated_at FROM sellers WHERE olx_user_id = $1
`

func (q *Queries) GetSellerByOlxID(ctx context.Context, olxUserID string) (Seller, error) {
	row := q.db.QueryRow(ctx, getSellerByOlxID, olxUserID)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.OlxUserID,
		&i.DisplayName,
		&i.ProfileUrl,
		&i.RegisteredAt,
		&i.IsBusiness,
		&i.PhoneHash,
		&i.AvatarUrl,
		&i.Location,
		&i.Raw,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.LastScrapedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSeller = `-- name: UpsertSeller :one
INSERT INTO sellers (
    olx_user_id,
    display_name,
    profile_url,
    is_business,
    phone_hash,
    avatar_url,
    location,
    raw,
    last_scraped_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, NOW()
)
ON CONFLICT (olx_user_id) DO UPDATE SET
    display_name    = EXCLUDED.display_name,
    profile_url     = EXCLUDED.profile_url,
    is_business     = EXCLUDED.is_business,
    phone_hash      = EXCLUDED.phone_hash,
    avatar_url      = EXCLUDED.avatar_url,
    location        = EXCLUDED.location,
    raw             = EXCLUDED.raw,
    last_seen_at    = NOW(),
    last_scraped_at = NOW()
RETURNING id, olx_user_id, display_name, profile_url, registered_at, is_business, phone_hash, avatar_url, location, raw, first_seen_at, last_seen_at, last_scraped_at, created_at, updated_at
`

type UpsertSellerParams struct {
	OlxUserID   string          `json:"olx_user_id"`
	DisplayName pgtype.Text     `json:"display_name"`
	ProfileUrl  pgtype.Text     `json:"profile_url"`
	IsBusiness  bool            `json:"is_business"`
	PhoneHash   pgtype.Text     `json:"phone_hash"`
	AvatarUrl   pgtype.Text     `json:"avatar_url"`
	Location    pgtype.Text     `json:"location"`
	Raw         json.RawMessage `json:"raw"`
}

// Insert a seller, or update the mutable fields if olx_user_id already
// exists. last_seen_at and last_scraped_at are bumped to NOW() on both
// insert and update; first_seen_at / created_at stay frozen (the schema
// defaults handle the insert case, ON CONFLICT leaves them untouched).
// updated_at is bumped automatically by the sellers_set_updated_at trigger.
func (q *Queries) UpsertSeller(ctx context.Context, arg UpsertSellerParams) (Seller, error) {
	row := q.db.QueryRow(ctx, upsertSeller,
		arg.OlxUserID,
		arg.DisplayName,
		arg.ProfileUrl,
		arg.IsBusiness,
		arg.PhoneHash,
		arg.AvatarUrl,
		arg.Location,
		arg.Raw,
	)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.OlxUserID,
		&i.DisplayName,
		&i.ProfileUrl,
		&i.RegisteredAt,
		&i.IsBusiness,
		&i.PhoneHash,
		&i.AvatarUrl,
		&i.Location,
		&i.Raw,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.LastScrapedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
